"""update to job

Revision ID: 247925620e24
Revises: 95e620458fcc
Create Date: 2019-04-18 11:56:04.623204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247925620e24'
down_revision = '95e620458fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('training', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'training')
    # ### end Alembic commands ###
